/**
 * Writes public/firebase-messaging-sw.js from root .env (VITE_FIREBASE_*).
 * Run before `vite` / `vite build` so the service worker matches your Firebase project.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const publicDir = path.join(root, "public");
const outFile = path.join(publicDir, "firebase-messaging-sw.js");
const pkgPath = path.join(root, "package.json");

function loadEnv() {
  const envPath = path.join(root, ".env");
  const out = {};
  if (!fs.existsSync(envPath)) return out;
  const raw = fs.readFileSync(envPath, "utf8");
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function firebaseSdkVersion() {
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    const v = pkg.dependencies?.firebase ?? pkg.devDependencies?.firebase ?? "12.12.0";
    return String(v).replace(/^[\^~]/, "").trim() || "12.12.0";
  } catch {
    return "12.12.0";
  }
}

const env = loadEnv();
const ver = firebaseSdkVersion();

const cfg = {
  apiKey: env.VITE_FIREBASE_API_KEY || "",
  authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || "",
  projectId: env.VITE_FIREBASE_PROJECT_ID || "",
  storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
  appId: env.VITE_FIREBASE_APP_ID || "",
};

const cfgJson = JSON.stringify(cfg);
const body = `/* Generated by scripts/write-fcm-sw.mjs — do not edit by hand */
importScripts('https://www.gstatic.com/firebasejs/${ver}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${ver}/firebase-messaging-compat.js');
firebase.initializeApp(${cfgJson});
const messaging = firebase.messaging();
messaging.onBackgroundMessage((payload) => {
  const n = payload.notification || {};
  const title = n.title || 'New pattern issue report';
  const options = {
    body: n.body || '',
    icon: n.icon,
    data: payload.data || {},
  };
  return self.registration.showNotification(title, options);
});
`;

if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(outFile, body, "utf8");
if (!cfg.projectId) {
  console.warn("[fcm:sw] Warning: no VITE_FIREBASE_PROJECT_ID in .env — service worker may not initialize.");
} else {
  console.log("[fcm:sw] Wrote", path.relative(root, outFile));
}
