/**
 * Writes public/firebase-messaging-sw.js from .env (VITE_FIREBASE_*).
 * Run via npm predev / prebuild so FCM works with the same config as src/firebase.ts.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const publicDir = path.join(root, "public");
const outFile = path.join(publicDir, "firebase-messaging-sw.js");

function loadDotEnv() {
  const envPath = path.join(root, ".env");
  const out = {};
  if (!fs.existsSync(envPath)) return out;
  const raw = fs.readFileSync(envPath, "utf8");
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fileEnv = loadDotEnv();
const env = { ...fileEnv, ...process.env };

const firebaseConfig = {
  apiKey: env.VITE_FIREBASE_API_KEY ?? "",
  authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? "",
  projectId: env.VITE_FIREBASE_PROJECT_ID ?? "",
  storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? "",
  messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? "",
  appId: env.VITE_FIREBASE_APP_ID ?? "",
};

const ver = "12.12.0";
const configJson = JSON.stringify(firebaseConfig);

const body = `/* Generated by scripts/write-fcm-sw.mjs — do not edit by hand */
/* eslint-disable no-undef */
importScripts(
  "https://www.gstatic.com/firebasejs/${ver}/firebase-app-compat.js",
  "https://www.gstatic.com/firebasejs/${ver}/firebase-messaging-compat.js",
);
firebase.initializeApp(${configJson});
const messaging = firebase.messaging();

// Activate new SW immediately so push handling matches the latest script.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

messaging.onBackgroundMessage((payload) => {
  console.log("[firebase-messaging-sw.js] onBackgroundMessage", payload);
  const n = payload.notification || {};
  const d = payload.data || {};
  const title = String(n.title || d.title || "FCM (background)").trim() || "FCM (background)";
  const bodyText =
    String(n.body || d.body || "").trim() ||
    (Object.keys(d).length ? JSON.stringify(d) : "") ||
    "New message (open Firebase Console payload if empty)";
  return self.registration
    .showNotification(title, {
      body: String(bodyText),
      icon: n.icon || d.icon,
      tag: String(d.tag || "fcm-bg-" + Date.now()),
      data: d,
      requireInteraction: false,
    })
    .then(() => console.log("[firebase-messaging-sw.js] showNotification OK"))
    .catch((err) => console.error("[firebase-messaging-sw.js] showNotification failed", err));
});
`;

fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(outFile, body, "utf8");
console.log("[fcm:sw] Wrote", path.relative(root, outFile));
